# Generated by Django 3.2.3 on 2021-05-30 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'Unknown'), ('1', 'Active'), ('2', 'Deactive')], default='0', editable=False, max_length=1)),
                ('name', models.CharField(max_length=255)),
                ('first_trade', models.DateTimeField()),
                ('market_cap', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('total_volume', models.FloatField()),
                ('total_trades', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_type', models.CharField(choices=[('0', 'USD'), ('1', 'BTC'), ('2', 'ETH')], default='0', editable=False, max_length=1)),
                ('price', models.FloatField()),
                ('price_date', models.DateTimeField()),
                ('volume_24h', models.FloatField()),
                ('PNL_24h', models.FloatField()),
                ('current_ATH', models.FloatField()),
                ('ATH_date', models.DateTimeField()),
                ('currency_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Market.currency')),
                ('market_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Market.market')),
            ],
        ),
    ]
