# Generated by Django 3.2.3 on 2021-06-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0002_auto_20210608_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='status',
            field=models.CharField(choices=[('0', 'Unknown'), ('1', 'Active'), ('2', 'Deactive')], default='0', editable=False, max_length=1),
        ),
    ]
