# Generated by Django 3.2.3 on 2021-06-08 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0003_market_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='status',
            field=models.CharField(choices=[('0', 'Unknown'), ('1', 'Active'), ('2', 'Deactive')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='currencymarket',
            name='currency_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Market.currency'),
        ),
        migrations.AlterField(
            model_name='currencymarket',
            name='currency_type',
            field=models.CharField(choices=[('0', 'USD'), ('1', 'BTC'), ('2', 'ETH')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='currencymarket',
            name='market_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Market.market'),
        ),
        migrations.AlterField(
            model_name='market',
            name='status',
            field=models.CharField(choices=[('0', 'Unknown'), ('1', 'Active'), ('2', 'Deactive')], default='0', max_length=1),
        ),
    ]
