# Generated by Django 3.1.4 on 2021-07-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0004_auto_20210608_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='currencymarket',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='market',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
