# Generated by Django 3.2.3 on 2021-06-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='name',
            field=models.CharField(default='x', max_length=31),
            preserve_default=False,
        ),
    ]
