# Generated by Django 3.2.3 on 2021-06-08 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0004_auto_20210608_1713'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Wallet', '0002_wallet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='walletitem',
            name='currencyMarket_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Market.currencymarket'),
        ),
        migrations.AlterField(
            model_name='walletitem',
            name='wallet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Wallet.wallet'),
        ),
    ]
