# Generated by Django 3.2.3 on 2021-06-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0003_auto_20210608_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='public_key',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
