# Generated by Django 3.1.4 on 2021-07-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0005_auto_20210629_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='walletitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
